### PR TITLE
Added coupling quality factor function

### PR DESCRIPTION
**Pull request by joelgrebel**

### CODE REVIEW

**Comment by edumur** [comment]
Nice piece of code!
I particularly appreciate the line 503 and 504.
A question: Where is the internal_quality_factor method called by the coupling_quality_factor one ?

**Comment by joelgrebel** [comment]
line 537

**Comment by edumur** [comment]
Ok, let me reformulate it ;) .
Line 537 you call a method "internal_quality_factor", where this method is defined ?

**Comment by joelgrebel** [comment]
good point, I added the method to the code

**Pull request merged**
